### ISSUE TITLE
Change active buttons to white background

### ISSUE THREAD

**Issue by marc-farre** [felixhahnweilheim/humhub-dark-mode#14]
In the marketplace we have:
![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/23310825/75cf0535-cf25-4315-9ab1-b174d7b5c76a)

It should be:
![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/23310825/21a716ab-ad53-4791-aa33-c062d8b2f280)

I think it's here, but I didn't test it on other pages:
https://github.com/felixhahnweilheim/humhub-dark-mode/blob/main/resources/DarkHumHub/less/theme.less#L176-L178

**Comment by felixhahnweilheim** [comment]
This line makes sense on many pages: Spaces page, People page, Module administration page, Module administration in spaces etc....
In these places the "active" buttons are used for elements that are already active (e.g. I am already member of the space). However in the Marketplace it is used for a button that should be clicked (Update).

So I'll simply add another line for the Marketplace.

**Comment by marc-farre** [comment]
Perfect, thanks!
