### ISSUE TITLE
Is it not applicable for v1.12.0?

### ISSUE THREAD

**Issue by yoshida-git-ai** [felixhahnweilheim/humhub-dark-mode#25]
I'm using a clean theme
Is it not applicable for v1.12.0?

**Comment by felixhahnweilheim** [comment]
Hi @yoshida-git-ai 
I have developped this module for HumHub version 1.15.
So I haven't tested it with older versions and can’t say if it works.

**Comment by ArchBlood** [comment]
If the module uses or extends classes that were introduced in v1.15 then this module wouldn't be usable in any older versions of HumHub and a compatibility check would have to be implemented if reverse compatibility were to be implemented.

**Comment by felixhahnweilheim** [comment]
Yes, and in this case also the stylesheets should be tested. Espacially because an older HumHub version also means there are some older modules.

If you really need backwards compatibility, you can
- test it at your own risk and create a PR
- ask me to do it as a paid service.
