### ISSUE TITLE
Pop-Up Windows don't follow style (dark)

### ISSUE THREAD

**Issue by ilocit** [felixhahnweilheim/humhub-dark-mode#30]
Hi Felix, 
first of all, thanks so much for building this nice Module for Humhub!
After installing I got some complaints from new users of my instance that they can not read the "Intro Guide for Newbies" - the content "disappeared".

This is what pop-up window content looks like with "dark" enabled.
![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/26718215/1278d2b7-c96d-48c0-8ab3-fb85c8f9fc64)

Running Humhub **v1.15** with **Clean theme**!

Maybe you can look into this?

**Comment by felixhahnweilheim** [comment]
Thank you for reporting the issue.
It will be solved in the next version (1.0.1).
It can take a few days until the new version is approved in the marketplace.

**Comment by felixhahnweilheim** [comment]
I missed the part that you are using the clean theme. @marc-farre would also have to release a new version of his theme including the dark theme update.

**Comment by marc-farre** [comment]
@felixhahnweilheim @ilocit  I've just released version 1.6.0 with CSS compiled for [Dark Module version 1.0.1](https://github.com/felixhahnweilheim/humhub-dark-mode/releases/tag/v1.0.1)

**Comment by ilocit** [comment]
You are just awesome, guys!
Fixed and working nicely!
![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/26718215/771add76-24a7-4464-960f-28a611c4091a)
