### ISSUE TITLE
Markdown Editor background color

### ISSUE THREAD

**Issue by ArchBlood** [felixhahnweilheim/humhub-dark-mode#32]
Include richtext fields, currently they show grey text on white background.

**Comment by felixhahnweilheim** [comment]
Can you give an example. Which rich text field?
or maybe a screenshot.

Because I don't see any richt text fields with white background in my tests.

**Comment by ArchBlood** [comment]
![Screenshot_20231125-044031.png](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/35392110/681cf18e-a7ff-4855-819a-57abf21b68b3)

**Comment by felixhahnweilheim** [comment]
Ok, I can’t reproduce this with the default theme (HumHub and HumHub (dark)).

![Screenshot_20231125_105447_Chrome.jpg](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/84990763/89d13aa4-e7af-41ae-a30e-0baabfd86c4a)

Maybe you can check in which order your browser has loaded the stylesheets? In my tests the dark 'theme.css' is always loaded after the theme.css but maybe that's not always the case.

Maybe adding an '!important' rule could solve the issue.

**Comment by ArchBlood** [comment]
Seems like it's an issue with the clean theme module.

**Comment by ArchBlood** [comment]
The stylesheet doesn't seem to update for the richtext field, it does however update for |`textInput()` fields. I use system settings if that helps any. :thinking:

**Comment by felixhahnweilheim** [comment]
It seems that your browser does not apply this line: https://github.com/felixhahnweilheim/humhub-dark-mode/blob/2e253f9f2edf1798340f745b9e48a66a66a8d009/resources/DarkHumHub/less/theme.less#L31

Testing with 'HumHub' as base theme and 'HumHub (dark)' in the module settings I really can not reproduce the bug.
When the `humhub-app.css` gets loaded after the dark `theme.css` a lot more backgrounds get white, not only the text editor.

Maybe you use any custom module which loads its own CSS?

**Comment by ArchBlood** [comment]
> It seems that your browser does not apply this line:
> 
> https://github.com/felixhahnweilheim/humhub-dark-mode/blob/2e253f9f2edf1798340f745b9e48a66a66a8d009/resources/DarkHumHub/less/theme.less#L31
> 
> Testing with 'HumHub' as base theme and 'HumHub (dark)' in the module settings I really can not reproduce the bug. When the `humhub-app.css` gets loaded after the dark `theme.css` a lot more backgrounds get white, not only the text editor.
> 
> Maybe you use any custom module which loads its own CSS?

Currently no, I've also checked to make sure for all instances when it comes to the richtext editor, but what I did find out is that this only happens for system admin. 🤔

If I impersonate another user everything is fine and works as intended, but not for system admin, this account was made through CLI, I'm not sure this is the issue though.

**Comment by felixhahnweilheim** [comment]
That gave me a hint! You use the 'simple' mode of the editor, do you?

I'll fix that as soon as possible.

**Comment by ArchBlood** [comment]
> That gave me a hint! You use the 'simple' mode of the editor, do you?
> 
> I'll fix that as soon as possible.

![Screenshot_20231129-080920.png](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/35392110/1a60e1d5-c02e-4692-8fc9-7fced9036ce4)

![Screenshot_20231129-080846.png](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/35392110/d5e78542-890d-4749-a007-02f138ef2e5a)

**Comment by ArchBlood** [comment]
So from looking at it, it's the markdown editor not the richtext editor!
