### ISSUE TITLE
Invalid path alias: @dark-mode\resources\DarkHumHub\css

### ISSUE THREAD

**Issue by ebillov** [felixhahnweilheim/humhub-dark-mode#38]
It seems like the issue was caused by the lines shown below. I needed to edit the directory separator to a forward-slash string and that solved the issue.

I am running on a local machine in Xampp for Windows.

![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/44574617/f059bf3b-0e92-4c32-9cd8-05a20b6509f6)

**Comment by felixhahnweilheim** [comment]
Thanks for the bug report.
I do not test on Windows but I'll release a patched version in the next days.

I was not aware that Yii handles compatibility with Windows without DIRECTORY_SEPERATOR

**Comment by felixhahnweilheim** [comment]
#39 should fix the issue (exactly as you proposed)

Could you also test it with the clean theme? That would be nice.
To make sure DIRECTORY_SEPERATOR in line 125 works with Windows.

**Comment by ebillov** [comment]
Hi @felixhahnweilheim I was using it on a clean Humhub theme. The dark theme works perfectly. Thank you. :)
