### ISSUE TITLE
support vcard module

### ISSUE THREAD

**Issue by felixhahnweilheim** [felixhahnweilheim/humhub-dark-mode#45]
see https://community.humhub.com/comment/perma?id=47472

**Comment by Gilbertdelyon** [comment]
+1 Same issue on our side
temporary workarround:
Add the following at the end of you theme.css file
```
.vcadBody{
color:#000;
}
```

**Comment by felixhahnweilheim** [comment]
I've added a PR to the Popover VCard module. Let's see if it gets merged. It would be the simplest and best solution.

**Comment by Gilbertdelyon** [comment]
Another workarround (but not a good practice!)
in `protected/modules/popover-vcard/ressources/humhub.vcard.popover.css` you van replace
```
.vcardBody {
    padding: 6px;
    border-top: 1px solid #c5c5c5;
}
```
with
```
.vcardBody {
    padding: 6px;
    border-top: 1px solid #c5c5c5;
   color:#000;
}
```

**Comment by felixhahnweilheim** [comment]
It will be solved in the next release of the VCard Popover module.
