### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by G-Burnett** [felixhahnweilheim/humhub-dark-mode#46]
Hi, HumHub generates an error message when trying to enable/disable Dark Mode from User Profile/General. Button on Top Bar works as normal.

![Dark](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/122267201/5d984bb8-944a-4245-bdfa-93058e0eb029)

**Comment by felixhahnweilheim** [comment]
Can you check if there is an error in the logs?

And maybe share which PHP version you use?
Strange that one is working, the other not...

**Comment by G-Burnett** [comment]
Please find attached error from log. This is running on a HubHub provisioned Demo instance, but my production instance has the same issue.

[darkerror.txt](https://github.com/felixhahnweilheim/humhub-dark-mode/files/14023008/darkerror.txt)

**Comment by felixhahnweilheim** [comment]
Okay, the error is with the message files. But normally it would appear everywhere not only in one form.

Do you have a special language?
Or any special settings concerning translations, languages?

Can you check that the message folder is present and the file base.php in your language folder is readable?
I can just imagine a file encoding problem...
I switched the German files to UTF8 with the last release (they were sonething else before by accident) to fix the Umlaute ä,ö,ü. And on my site everything works fine.

**Comment by G-Burnett** [comment]
Hi Felix, The HumHub demo site was only set up yesterday and is running in English UK language, I am presuming all folder permissions are correct. My production is running English UK too and no other modules in production setup is producing errors.
Sorry to be a pain!
Gary

**Comment by G-Burnett** [comment]
Getting the same error when language changed to German.

**Comment by felixhahnweilheim** [comment]
Ok, I was a bit stupid.
I mixed up the modules. Of course it should not be 'VerifiedModule.base', sorry.
I'll create a fixed release when I am at my laptop again. (currently at an audition in Hungary)

**Comment by felixhahnweilheim** [comment]
The error is in views/user/form.php line 15

**Comment by G-Burnett** [comment]
Sounds exciting :-) Thank you, no panic.
