### ISSUE TITLE
Clean Theme Dark Mode Issue

### ISSUE THREAD

**Issue by mansoorih** [felixhahnweilheim/humhub-dark-mode#54]
Since the Clean Theme update came in a couple of weeks back, when we click on alert notifications, the icon does not display proper contrast color in dark mode for the text (as visible in screenshot). We have other users also complain about this same issue. 

This happens for ‘**New**’ notifications. When we click on ‘**Mark all as seen**’, the color works properly. Perhaps, this is a CSS bug for color contrast for the latest clean-theme making it highly inconvenient to use the dark mode.

![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/92026716/8f725fc9-c18b-4af6-80aa-9348cd81e7d4)

**Comment by felixhahnweilheim** [comment]
Thanks for reporting this issue!

I have added an issue in the clean theme repo (I think the error has to be solved there.)
So I'll close this issue here.

**Comment by marc-farre** [comment]
@mansoorih the issue has been fixed by @felixhahnweilheim
The fix has been published in [version 1.7.4](https://github.com/cuzy-app/clean-theme/releases/tag/1.7.4) which is now available on [the marketplace](https://marketplace.humhub.com/module/clean-theme/description).

**Comment by mansoorih** [comment]
@marc-farre , @felixhahnweilheim - doesn't look the issue got fixed after the module update. I had cleared cache and cookies to double-check. Had logged off and logged back in. See latest screenshot.

![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/92026716/84adfcec-7ea8-4ef1-9b45-70ff7fb1208c)

**Comment by marc-farre** [comment]
@mansoorih I'm not having the issue.
If you have a custom child theme, recompile the CSS.
Check that you don't have a dark mode extension for your browser.
If you use directly the Clean Theme module, check you have the same theme selected in:
- Administration -> Settings -> Appearance
- Administration -> Modules -> Dark mode -> Configuration

**Comment by mansoorih** [comment]
My installation is plain vanilla HumHub CE and I just apply standard stable updates. The dark mode is only in HumHub, not in browser. I have no developer to make any custom changes. Here are the screenshots.

![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/92026716/cb5aceef-69bd-49dc-a3fc-e58dbbf7c759)


![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/92026716/09517f0c-e71d-4a08-9ad8-7c2baf872e38)

**Comment by marc-farre** [comment]
@mansoorih Thanks for these details.
You're right, the issue was still remaining for the Clean Base theme (it was solved for "Contrasted" and "Bordered" only).
Please upgrade Clean Theme to version 1.7.5.
