### ISSUE TITLE
Button to login with SSO is dark with a dark text color

### ISSUE THREAD

**Issue by marc-farre** [felixhahnweilheim/humhub-dark-mode#55]
![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/23310825/3b4f7f17-e209-41a1-931b-94f5ffe6a8fc)

@felixhahnweilheim tell me if I can help. I'm not quite sure what to change without impacting other pages.

This is what would be correct, I think:

![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/23310825/a99c2c9f-22db-4a05-bda4-62f330793455)

**Comment by felixhahnweilheim** [comment]
Thanks for reporting.

https://github.com/humhub/humhub/pull/6886 introduced a new LESS variable @text-color-default which is still missing in the dark mode.
I would set that to nearly white, maybe #fafafa, or even white.

I can do that the next days.

**Comment by felixhahnweilheim** [comment]
https://github.com/felixhahnweilheim/humhub-dark-mode/commit/a236299ac0ab97747117d362c4d2852c140ca00b should fix the issue.

Could you please test if everything looks good now with the Keycloak module? I don't use it myself.

You suggested to make the background white. But that the button would stand out very much. I think `btn-default` should be less highlighted than `btn-primary` and `btn-secondary`.

Additionally I have also improved the "OR" container in the login modal window, so it is also dark with white text color:
![Screenshot 2024-05-12 at 22-20-47](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/84990763/bead2c0c-f716-495f-8602-f4039d112d22)

**Comment by marc-farre** [comment]
@felixhahnweilheim Thanks!
