### ISSUE TITLE
Dark mode doesn't work with other plugins such us: Classified Space

### ISSUE THREAD

**Issue by ilMagnifico** [felixhahnweilheim/humhub-dark-mode#58]
plugin that doesn't integrate well: https://marketplace.humhub.com/module/classified-space/screenshots.

Since as it shows on the image, it shows the list of the spaces with a white background instead of a black one. Could you please adapt it? Thanks.

<img width="974" alt="Screenshot 2024-07-29 alle 15 07 08" src="https://github.com/user-attachments/assets/7fed8b14-1b2b-4c6d-844c-6f216f3b7d6a">

**Comment by felixhahnweilheim** [comment]
Thanks @marc-farre 
So I have closed the issue. For issues with other modules please create a new issue.

**Comment by marc-farre** [comment]
@felixhahnweilheim FYI I'm reviewing all my modules to use the new CSS variables instead of the PHP `$this->theme->variable()` method.

**Comment by marc-farre** [comment]
@felixhahnweilheim I've also created an issue for HumHub modules: https://github.com/humhub/humhub/issues/7143
